services:
  petrolette:
    build: .
    # ports:
      # - 8010:8000
    labels:
      - "traefik.enable=true" 
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.test_machine.tls.certresolver=myresolver"
      - "traefik.http.services.test_machine.loadbalancer.server.port=8000"
      - "traefik.http.routers.test_machine.rule=Host(`$DOMAIN`)"
    command: "bash start.sh"
